import test from 'node:test';
import assert from 'node:assert/strict';
import {serialNormalizer} from '../src/engine/serialNormalizer.js';
import {normalizeDate} from '../src/engine/fieldExtractor.js';
import {matrixValidator} from '../src/engine/matrixValidator.js';
import {statusEngine,applyStatus} from '../src/engine/statusEngine.js';
import {prepare,DemoRepository} from '../src/adapters/repository.js';
import {analyze} from '../src/engine/pipeline.js';
const ev=(id,type,date,final='CONFORME')=>({id,type,date,createdAt:'2026-10-01T00:00:00.000Z',fields:{finalConformity:final}});
test('serial conserva ceros y guiones; normaliza espacios y mayúsculas',()=>{assert.equal(serialNormalizer(' 001-abc '),'001-ABC');assert.notEqual(serialNormalizer('001-ABC'),serialNormalizer('001ABC'));});
test('fechas reales en formatos español, NOV e ISO',()=>{assert.equal(normalizeDate('22-Feb-2025'),'2025-02-22');assert.equal(normalizeDate('01.09.2026'),'2026-09-01');assert.equal(normalizeDate('31/02/2026'),'');assert.equal(normalizeDate('2026-02-30'),'');});
test('reparación emitida deja operativa y BHA no cambia estado',()=>{const repair=ev('r','REPAIR','2026-09-01');assert.equal(statusEngine([repair,ev('b','BHA','2026-10-01')]).status,'OPERATIVA');assert.equal(statusEngine([ev('b','BHA','2026-10-01')]).status,'SIN_ESTADO_TECNICO');});
test('inspección posterior domina; importación antigua no retrocede estado',()=>{const events=[ev('i','INSPECTION','2026-09-21','NO_CONFORME_REPARABLE'),ev('r','REPAIR','2026-09-01')];const result=statusEngine(events);assert.equal(result.status,'NO_CONFORME_REPARABLE');assert.deepEqual(applyStatus(result,events[1]),result);assert.equal(statusEngine([...events,ev('x','INSPECTION','2026-09-24','NO_CONFORME_FUERA_SERVICIO')]).status,'NO_CONFORME_FUERA_SERVICIO');});
test('reparación posterior recupera herramienta; empates deterministas',()=>{assert.equal(statusEngine([ev('i','INSPECTION','2026-09-01','NO_CONFORME_FUERA_SERVICIO'),ev('r','REPAIR','2026-09-02')]).status,'OPERATIVA');const i=ev('i','INSPECTION','2026-09-02','NO_CONFORME_REPARABLE');i.createdAt='2026-10-02';assert.equal(statusEngine([i,ev('r','REPAIR','2026-09-02')]).status,'NO_CONFORME_REPARABLE');});
test('validación bloquea reparación sin empresa y fechas incoherentes',()=>{assert(matrixValidator('REPAIR',{serial:'134333N',fields:{}}).some(e=>e.includes('issuer')));assert(matrixValidator('INSPECTION',{serial:'ABC001',fields:{inspectionDate:'2026-09-22',issueDate:'2026-09-21'}}).some(e=>e.includes('preceder')));});
function draft(id='a'){return {id,name:'repair.pdf',type:'REPAIR',template:'NOV_TUBOSCOPE_HW',records:[{serial:'001ABC',reviewed:true,fields:{issuer:'NOV',reportNumber:'R1',workOrder:'WO1',repairDate:'2026-09-01',pin:'OK',box:'OK',machining:'Reface'},evidence:[]}]};}
test('valida sin confirmación individual y rechaza serial repetido',async()=>{const d=draft();d.records[0].reviewed=false;assert.equal((await prepare(d)).events.length,1);d.records.push({...d.records[0]});await assert.rejects(prepare(d),/repetido/);});
test('repositorio separa entidades y bloquea duplicados de evento y documento',async()=>{let storage=null;globalThis.localStorage={getItem:()=>storage,setItem:(k,v)=>{storage=v;}};const repo=new DemoRepository();await repo.save(draft());const s=await repo.load();assert.equal(s.tools[0].status,'OPERATIVA');assert.equal(s.events.length,1);assert.equal(s.documents.length,1);assert.equal(s.bha.length,0);await assert.rejects(repo.save(draft()),/PDF ya/);await assert.rejects(repo.save(draft('b')),/Ya existe un evento/);assert.equal((await repo.load()).documents.length,1);});
test('BHA crea cabecera, miembros y eventos sin estado técnico',async()=>{let storage=null;globalThis.localStorage={getItem:()=>storage,setItem:(k,v)=>{storage=v;}};const repo=new DemoRepository();const d={id:'bha1',name:'bha.pdf',type:'BHA',template:'ECOPETROL_BHA',records:[{serial:'01234',reviewed:true,evidence:[],fields:{bhaNumber:'30',bhaType:'MWD',well:'UF19X',phase:'12',bhaDate:'2026-09-22',component:'HWDP'}}]};await repo.save(d);const s=await repo.load();assert.equal(s.bha.length,1);assert.equal(s.bhaMembers.length,1);assert.equal(s.tools[0].status,'SIN_ESTADO_TECNICO');});
test('TQC tabla multi-serial divide y conserva evidencia PIN y BOX',()=>{const pages=[{page:1,text:'TOTAL QC SAS\nFT-END-003 Versión:002 Fecha: 22-Feb-2025\nCertificado de inspección N°472209260006\nFecha inspección 21/09/2026\nFecha emisión 22/09/2026\n9.1 CUERPO\n1 NHAF34175 OK Conforme Conforme Conforme Conforme\n2 107840N OK Conforme Conforme Conforme Conforme'},{page:2,text:'9.2 TOOL JOINT - PIN\n1 NHAF34175 OK Conforme\n2 107840N OK Conforme'},{page:3,text:'9.3 TOOL JOINT - BOX\n1 NHAF34175 OK Conforme\n2 107840N OK Conforme'}];const result=analyze(pages);assert.equal(result.type,'INSPECTION');assert.equal(result.records.length,2);assert.equal(result.records[0].fields.pin,'Conforme');assert.equal(result.records[0].fields.box,'Conforme');assert.equal(result.records[0].evidence.length,3);});
test('serial numérico BHA y guiones; no acepta Varíos como herramienta',()=>{const result=analyze([{page:1,text:'COMPONENTES BHA\nCOMPONENTE BHA Nº: 30 CONVENCIONAL LOCACIÓN: UF19X\nFECHA: 22/09/2026 FASE: 12\n239400 8 5/16" 2 7/8" 3,11 30,73\nCROSSOVER H&P TMS-0615-5 7" 2 7/8" 2,06 3,12'}]);assert.deepEqual(result.records.map(r=>r.serial),['239400','TMS-0615-5']);assert.equal(analyze([{page:1,text:'Certificado de inspección\nSerial: Varios'}]).records.length,0);});
test('matriz BHA rechaza medidas inválidas e inspección conforme contradictoria',()=>{
 assert(matrixValidator('BHA',{serial:'ABC001',fields:{length:'-10',outerDiameter:'8 1/0'}}).filter(e=>e.includes('Medida inválida')).length===2);
 assert(matrixValidator('BHA',{serial:'ABC001',fields:{outerDiameter:'8 1/4"',innerDiameter:'3,5'}}).every(e=>!e.includes('Medida inválida')));
 assert(matrixValidator('INSPECTION',{serial:'ABC001',fields:{finalConformity:'CONFORME',pin:'No conforme / reparable'}}).some(e=>e.includes('contradice')));
});
