import {calendarActivities,timelineSeries,eventTypes} from '../engine/calendar.js';
const names={INSPECTION:'Inspección',REPAIR:'Reparación',BHA:'BHA'};
const colors={INSPECTION:'#5d2a1a',REPAIR:'#17191c',BHA:'#777b86'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const localDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const pretty=d=>d.split('-').reverse().join('/');
export function chartTicks(points){
 const start=Date.parse(points[0].date),span=Date.parse(points.at(-1).date)-start;
 if(!span)return [{x:460,date:points[0].date}];
 const days=Math.round(span/86400000),count=Math.min(4,days);
 return Array.from({length:count+1},(_,i)=>{const day=Math.round(days*i/count);return {x:65+day/days*790,date:new Date(start+day*86400000).toISOString().slice(0,10)};});
}
export function chartView(data){
 const points=timelineSeries(data);if(!points.length)return '<section class="panel"><h2>Actividad documental</h2><p>El gráfico aparecerá al cargar tus reportes.</p></section>';
 const max=Math.max(1,...points.flatMap(p=>eventTypes.map(t=>p[t]))),start=Date.parse(points[0].date),span=Date.parse(points.at(-1).date)-start;
 const x=p=>span?65+(Date.parse(p.date)-start)/span*790:460,y=n=>210-n/max*160;
 const activities=calendarActivities(data).filter(e=>!e.planned);
 return `<section class="panel"><div class="panel-title"><div><h2>Actividad documental</h2><p class="muted">Acércate a un punto o tócalo para ver sus reportes.</p></div></div><div class="chart-legend">${eventTypes.map(t=>`<span><i style="background:${colors[t]}"></i>${names[t]}</span>`).join('')}</div><div class="chart-scroll"><div class="chart-stage"><svg class="activity-chart" viewBox="0 0 920 275" role="group" aria-label="Reportes por fecha. Selecciona un punto para consultar los eventos.">${[0,1,2,3,4].map(i=>`<line x1="65" x2="855" y1="${y(max*i/4)}" y2="${y(max*i/4)}"/><text x="48" y="${y(max*i/4)+4}" text-anchor="end">${Number((max*i/4).toFixed(1))}</text>`).join('')}${eventTypes.map(t=>`<polyline fill="none" stroke="${colors[t]}" stroke-width="3" stroke-dasharray="${t==='REPAIR'?'8 4':t==='BHA'?'2 4':'none'}" points="${points.map(p=>`${x(p)},${y(p[t])}`).join(' ')}"/>${points.filter(p=>p[t]>0).map(p=>`<circle class="chart-point" data-chart-date="${p.date}" cx="${x(p)}" cy="${y(p[t])}" r="6" fill="${colors[t]}" tabindex="0" role="button" aria-expanded="false" aria-label="${names[t]}, ${pretty(p.date)}, ${p[t]} reportes"/>`).join('')}`).join('')}${chartTicks(points).map(p=>`<text class="chart-tick" x="${p.x}" y="250" text-anchor="middle">${pretty(p.date)}</text>`).join('')}</svg>${points.map(p=>`<div class="chart-card" data-chart-card="${p.date}" hidden role="region" aria-label="Eventos del ${pretty(p.date)}"><div class="chart-card-heading"><b>${pretty(p.date)}</b><button class="subtle" data-close-chart aria-label="Cerrar tarjeta">✕</button></div>${activities.filter(a=>a.date===p.date).map(a=>{const e=data.events.find(e=>e.documentId===a.documentId&&e.date===a.date),f=e?.fields||{};return `<article><span>${names[a.type]} · ${a.serials.length} serial${a.serials.length===1?'':'es'}</span><button class="document-link" data-report="${esc(a.documentId)}">${esc(f.certificateNumber||f.reportNumber||(f.bhaNumber?'BHA '+f.bhaNumber:a.title))} ↗</button><p>${esc(f.issuer||f.well||'')}</p><small>${esc(a.serials.join(', '))}</small></article>`;}).join('')}</div>`).join('')}</div></div><details><summary>Ver datos del gráfico</summary><div class="table-wrap"><table><thead><tr><th>Fecha</th>${eventTypes.map(t=>`<th>${names[t]}</th>`).join('')}</tr></thead><tbody>${points.map(p=>`<tr><td>${pretty(p.date)}</td>${eventTypes.map(t=>`<td>${p[t]}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></section>`;
}
export function calendarView(data,month,selected){
 const [year,m]=month.split('-').map(Number),days=new Date(year,m,0).getDate(),offset=(new Date(year,m-1,1).getDay()+6)%7,activities=calendarActivities(data),dayEvents=activities.filter(e=>e.date===selected);
 const title=new Intl.DateTimeFormat('es-CO',{month:'long',year:'numeric'}).format(new Date(year,m-1,1));
 return `<div class="page-heading"><h1>Calendario</h1><button class="primary" data-action="new-schedule">+ Agendar evento</button></div><section class="panel"><div class="panel-title"><button class="secondary" data-month="-1" aria-label="Mes anterior">←</button><h2>${title}</h2><div class="row-actions"><button class="subtle" data-action="calendar-today">Hoy</button><button class="secondary" data-month="1" aria-label="Mes siguiente">→</button></div></div><div class="calendar-week">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=>`<span>${d}</span>`).join('')}</div><div class="calendar-grid">${'<div></div>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,items=activities.filter(a=>a.date===date);return `<button class="calendar-day ${date===localDay()?'today':''}" data-day="${date}" aria-pressed="${selected===date}" aria-label="${pretty(date)}, ${items.length} eventos"><b>${i+1}</b><div>${eventTypes.map(t=>{const total=items.filter(a=>a.type===t).length;return total?`<span class="calendar-dot" style="background:${colors[t]}" title="${names[t]}: ${total}">${total}</span>`:'';}).join('')}</div>${items.some(a=>a.planned)?'<small>Agendado</small>':''}</button>`;}).join('')}</div><div class="chart-legend">${eventTypes.map(t=>`<span><i style="background:${colors[t]}"></i>${names[t]}</span>`).join('')}</div></section><section class="panel"><div class="panel-title"><h2>${pretty(selected)}</h2><button class="subtle" data-action="new-schedule">Agendar aquí +</button></div>${dayEvents.length?dayEvents.map(e=>`<article class="calendar-event"><div><span class="badge ${e.planned?'warning':'success'}">${e.planned?'Programado':'Registrado'} · ${names[e.type]}</span><h3>${esc(e.title)}</h3><p>${e.serials.length?esc(e.serials.join(', ')):'Sin serial específico'}</p>${e.notes?`<p>${esc(e.notes)}</p>`:''}</div><div class="row-actions">${e.planned?`<button class="subtle" data-schedule-edit="${esc(e.id)}">Editar</button><button class="subtle" data-schedule-delete="${esc(e.id)}">Cancelar cita</button>`:`<button class="secondary" data-report="${esc(e.documentId)}">Ver reporte</button>`}</div></article>`).join(''):'<p class="muted">No hay eventos para este día.</p>'}</section>`;
}
export function scheduleForm(entry={}){return `<h2>${entry.id?'Editar':'Agendar'} evento</h2><form id="schedule-form"><input type="hidden" name="id" value="${esc(entry.id||'')}"><label>Título<input name="title" required maxlength="160" value="${esc(entry.title)}"></label><div class="fields"><label>Fecha<input type="date" name="date" required value="${esc(entry.date)}"></label><label>Tipo<select name="type">${eventTypes.map(t=>`<option value="${t}" ${entry.type===t?'selected':''}>${names[t]}</option>`).join('')}</select></label><label>Serial (opcional)<input name="serial" maxlength="64" value="${esc(entry.serial)}"></label></div><label>Notas<textarea name="notes" maxlength="2000">${esc(entry.notes)}</textarea></label><div class="row-actions"><button type="button" data-action="dismiss-dialog" class="secondary">Volver</button><button class="primary">Guardar evento</button></div></form>`;}
