import './views/chartInteraction.js';
import {chartView,calendarView,scheduleForm,localDay} from './views/calendarViews.js';
import './style.css';
import './steep.css';
import {toolGroup} from './engine/toolGroup.js';
import {reportModel} from './export/reportModel.js';
import {downloadExcel} from './export/xlsx.js';
import {configured,session,FirebaseRepository} from './adapters/firebase.js';
import {DemoRepository,digest,documentErrors,emptyState} from './adapters/repository.js';
import {pdfStore,archive} from './adapters/pdfStore.js';
import {textExtractor} from './engine/textExtractor.js';
import {analyze} from './engine/pipeline.js';
import {fieldDefinitions} from './engine/fieldExtractor.js';
import {matrixValidator,states} from './engine/matrixValidator.js';
import {historyEngine} from './engine/historyEngine.js';
import {serialNormalizer} from './engine/serialNormalizer.js';
const root=document.querySelector('#app');
let user=null,repo=null,data=emptyState(),demo=false,page='dashboard',inbox=[],failures=[],search='',detail='',reportId='',editor=null,busy=false,progress='',authMode='login',pdfUrl='',installPrompt,epoch=0;
let calendarMonth=localDay().slice(0,7),selectedDay=localDay();
let groupFilter='ALL',documentFilter='ALL';
let pendingWrite=Promise.resolve();
const labels={INSPECTION:'Inspección',REPAIR:'Reparación',BHA:'BHA',UNKNOWN:'Sin clasificar',OPERATIVA:'Operativa',CONFORME:'Conforme',NO_CONFORME_REPARABLE:'No conforme · reparable',NO_CONFORME_FUERA_SERVICIO:'Fuera de servicio',SIN_ESTADO_TECNICO:'Sin estado técnico'};
const commonKeys={INSPECTION:['certificateNumber','formatCode','formatVersion','versionDate','issuer','inspectionDate','issueDate'],REPAIR:['issuer','reportNumber','workOrder'],BHA:['bhaNumber','well','phase','bhaDate']};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?v.split('-').reverse().join('/'):'—';
const owner=()=>demo?'demo':user.uid;
const pending=()=>inbox.filter(x=>!data.documents.some(d=>d.id===x.id)&&x.status!=='saved');
const humanError=value=>String(value).replace(/\b[a-zA-Z]+\b/g,key=>Object.values(fieldDefinitions).flat().find(([k])=>k===key)?.[1]||key);
function notify(message){const el=document.querySelector('#notice');el.textContent=humanError(message);el.classList.add('visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('visible'),6500);}
function status(value){return `<span class="badge ${value.includes('FUERA')?'danger':value.includes('REPARABLE')?'warning':value==='SIN_ESTADO_TECNICO'?'neutral':'success'}">${esc(labels[value]||value)}</span>`;}
function heading(title,action='',subtitle=''){return `<div class="page-heading"><div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${action}</div>`;}
function shell(content){return `<div class="layout"><div class="factory-topbar"><div class="factory-topbar-inner"><a class="brand"><span class="mark">T<span>•</span></span>ToolTrace</a><nav>${[['dashboard','◫','Resumen'],['upload','↥','Cargar PDFs'],['tools','⌕','Herramientas'],['documents','▤','Documentos'],['calendar','▦','Calendario']].map(([key,icon,title])=>`<button data-page="${key}" class="${page===key||(editor&&key==='documents')?'active':''}"><span aria-hidden="true">${icon}</span>${title}${key==='documents'&&pending().length?`<small>${pending().length}</small>`:''}</button>`).join('')}</nav></div></div><main><header><span title="${esc(user.email)}">${demo?'ARCHIVO LOCAL':'MI ESPACIO'} / ${({dashboard:'Resumen',upload:'Cargar PDFs',tools:'Herramientas',documents:'Documentos',calendar:'Calendario'}[page])}</span><div><span class="network">${navigator.onLine?'En línea':'Sin conexión'}</span> <button data-action="install" class="subtle">Instalar app</button> <button data-action="logout" class="subtle mobile-logout" ${busy?'disabled':''}>Salir</button></div></header>${busy?`<div class="progress-strip" role="status">${esc(progress||'Guardando…')}</div>`:''}${content}</main></div>`;}
function authView(){const titles={login:'Tu operación, en una sola vista.',register:'Crea tu cuenta.',reset:'Recupera tu acceso.'};return `<div class="auth"><section class="auth-story"><a class="brand"><span class="mark">T<span>•</span></span>ToolTrace</a><p class="eyebrow">DEL DOCUMENTO AL HISTORIAL</p><h1>Cada serial.<br>Cada evento.<br>Una historia clara.</h1><p>Conecta inspecciones, reparaciones y ensamblajes BHA con el expediente de cada herramienta.</p><div class="story-card"><span class="badge success">Trazabilidad completa</span><div class="trace"><i></i><div><b>01 / Inspección</b><p>Condición técnica documentada</p></div></div><div class="trace"><i></i><div><b>02 / Reparación</b><p>Herramienta operativa</p></div></div><div class="trace"><i></i><div><b>03 / BHA</b><p>Historial de uso y composición</p></div></div></div><small></small></section><section class="auth-form"><p class="eyebrow">BIENVENIDO A TOOLTRACE</p><h2>${titles[authMode]}</h2><p>${authMode==='reset'?'Te enviaremos un enlace para restablecer la contraseña.':'Accede a tu espacio de trazabilidad documental.'}</p>${!configured?'<div class="callout">Conecta Firebase para usar tu cuenta.</div>':''}<form id="auth-form"><label>Correo electrónico<input name="email" type="email" autocomplete="email" required placeholder="nombre@empresa.com"></label>${authMode!=='reset'?`<label>Contraseña<input name="password" type="password" autocomplete="${authMode==='register'?'new-password':'current-password'}" minlength="${authMode==='register'?10:1}" required placeholder="${authMode==='register'?'Mínimo 10 caracteres':'Tu contraseña'}"></label>`:''}<button class="primary" ${!configured?'disabled':''}>${authMode==='login'?'Iniciar sesión →':authMode==='register'?'Crear cuenta →':'Enviar enlace →'}</button></form><div class="auth-links">${authMode==='login'?'<button data-auth="reset">Olvidé mi contraseña</button><button data-auth="register">Crear una cuenta</button>':'<button data-auth="login">Volver a iniciar sesión</button>'}</div><hr><button data-action="demo" class="secondary wide">Explorar demostración local</button><small>Datos guardados en este dispositivo.</small></section></div>`;}

function toolRows(list){return list.length?`<div class="table-wrap"><table><thead><tr><th>Serial</th><th>Grupo</th><th>Estado</th><th>Fecha técnica</th><th>Eventos</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><button class="serial-link" data-serial="${esc(t.serial)}">${esc(t.serial)}</button></td><td><span class="group-badge">${toolGroup(t.serial)}</span></td><td>${status(t.status)}</td><td>${date(t.statusDate)}</td><td>${data.events.filter(e=>e.serial===t.serial).length}</td><td><button data-serial="${esc(t.serial)}" class="subtle">Ver ficha ↗</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h3>No hay seriales en esta vista</h3><button class="primary" data-page="upload">Cargar PDFs</button></div>';}
function dashboard(){return heading('Resumen','<button class="primary" data-page="upload">+ Cargar PDFs</button>')+`<section class="metrics">${[['Herramientas',data.tools.length],['Documentos',data.documents.length],['Eventos',data.events.length],['No conformes',data.tools.filter(t=>t.status.startsWith('NO_CONFORME')).length]].map(([name,count])=>`<article><span>${name}</span><strong>${count}</strong></article>`).join('')}</section>${pending().length?`<div class="attention-bar"><span>${pending().length} documento(s) requieren atención</span><button class="subtle" data-page="documents">Ver pendientes →</button></div>`:''}${chartView(data)}`;}
function filteredTools(){return data.tools.filter(t=>(groupFilter==='ALL'||toolGroup(t.serial)===groupFilter)&&t.serial.includes(serialNormalizer(search))).sort((a,b)=>toolGroup(a.serial).localeCompare(toolGroup(b.serial))||a.serial.localeCompare(b.serial));}
function groupTabs(){return `<div class="filter-tabs" aria-label="Grupo de herramientas">${[['ALL','Todas'],['HWDP','HWDP'],['OTRAS','Otras']].map(([key,label])=>`<button data-group="${key}" aria-pressed="${groupFilter===key}">${label} <small>${data.tools.filter(t=>key==='ALL'||toolGroup(t.serial)===key).length}</small></button>`).join('')}</div>`;}
function excelButton(view=false){return `<button class="secondary" data-action="excel" ${view?'data-scope="view"':''}>↓ Excel${view?' de esta vista':''}</button>`;}
function flow(){return `<div class="document-flow"><div><span>1</span><b>Carga tus PDFs</b></div><div class="${busy?'processing':''}"><span>2</span><b>Lectura automática</b></div><div><span>3</span><b>Consulta y edita</b></div></div>`;}
function documentTabs(){return `<div class="filter-tabs" aria-label="Estado del documento">${[['ALL','Todos',library().length],['saved','Guardados',data.documents.length],['pending','Por completar',pending().length]].map(([key,label,count])=>`<button data-doc-filter="${key}" aria-pressed="${documentFilter===key}">${label} <small>${count}</small></button>`).join('')}</div>`;}
function searchBox(){return `<label class="search"><span aria-hidden="true">⌕</span><input id="search" value="${esc(search)}" placeholder="Buscar serial" aria-label="Buscar serial"></label>`;}
function toolsView(){return heading('Herramientas',excelButton(true))+`<section class="panel">${groupTabs()}${searchBox()}<div id="tool-results">${toolRows(filteredTools())}</div></section>`;}
function library(){const map=new Map(inbox.map(x=>[x.id,x]));for(const d of data.documents)map.set(d.id,{...d,status:'saved'});return [...map.values()].sort((a,b)=>(b.uploadedAt||b.createdAt||'').localeCompare(a.uploadedAt||a.createdAt||''));}
function documentRows(documents){return documents.length?`<div class="table-wrap"><table><thead><tr><th>Documento</th><th>Tipo</th><th>Seriales</th><th>Estado</th><th></th></tr></thead><tbody>${documents.map(d=>{const saved=data.documents.some(x=>x.id===d.id)||d.status==='saved';return `<tr><td><button class="document-link" data-report="${esc(d.id)}">${esc(d.name)}</button></td><td>${labels[d.type]||'Sin clasificar'}</td><td>${d.recordCount??d.records?.length??0}</td><td><span class="badge ${saved?'success':'warning'}">${saved?'Guardado':d.status==='queued'?'En cola':d.status==='waiting'?'Por sincronizar':'Por completar'}</span></td><td><div class="row-actions"><button class="subtle" data-pdf="${esc(d.id)}">PDF</button><button class="subtle" data-edit="${esc(d.id)}" ${busy?'disabled':''}>${saved?'Editar':'Completar'}</button></div></td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty"><p>No hay documentos.</p></div>';}
function documentsView(){return heading('Documentos',`<div class="row-actions">${excelButton()}<button class="secondary danger-button" data-action="erase-start">Eliminar datos</button><button class="primary" data-page="upload">+ Cargar PDFs</button></div>`)+`${flow()}<section class="panel">${documentTabs()}${documentRows(library().filter(d=>documentFilter==='ALL'||(documentFilter==='saved'?d.status==='saved':d.status!=='saved')))}</section>`;}
function upload(){return heading('Cargar PDFs')+`${flow()}<section class="dropzone"><span aria-hidden="true">↥</span><h2>Selecciona o arrastra tus PDFs</h2><p>Se validan y guardan automáticamente.</p><label class="primary file-label">Seleccionar PDFs<input id="files" type="file" accept="application/pdf,.pdf" multiple ${busy?'disabled':''}></label><small>Máximo 25 MB por archivo</small></section>${failures.length?`<div class="callout danger">${failures.map(f=>`<p>${esc(f)}</p>`).join('')}</div>`:''}<section class="panel"><div class="panel-title"><h2>Documentos cargados</h2><button class="subtle" data-page="documents">Ver todos →</button></div>${documentRows(library())}</section>`;}
function eventRows(events,type){return `<div class="table-wrap"><table><thead><tr><th>Serial</th><th>Fecha</th>${type==='BHA'?'<th>OD (in)</th><th>ID (in)</th><th>Longitud (ft)</th>':'<th>Resultado</th><th>PIN</th><th>BOX</th>'}</tr></thead><tbody>${events.map(e=>`<tr><td><button class="serial-link" data-serial="${esc(e.serial)}">${esc(e.serial)}</button></td><td>${date(e.date)}</td>${type==='BHA'?`<td>${esc(e.fields.outerDiameter||'—')}</td><td>${esc(e.fields.innerDiameter||'—')}</td><td>${esc(e.fields.length||'—')}</td>`:`<td>${status(e.type==='REPAIR'?'OPERATIVA':e.fields.finalConformity||'SIN_ESTADO_TECNICO')}</td><td>${esc(e.fields.pin||'—')}</td><td>${esc(e.fields.box||'—')}</td>`}</tr>`).join('')}</tbody></table></div>`;}
function reportView(){const doc=data.documents.find(d=>d.id===reportId);if(!doc)return documentsView();const events=data.events.filter(e=>e.documentId===doc.id);const f=events[0]?.fields||{};return `<button class="subtle" data-page="documents">← Documentos</button>`+heading(esc(f.certificateNumber||f.reportNumber||(f.bhaNumber?'BHA '+f.bhaNumber:doc.name)),`<div class="row-actions"><button class="secondary" data-pdf="${esc(doc.id)}">Ver PDF</button><button class="primary" data-edit="${esc(doc.id)}" ${busy?'disabled':''}>Editar reporte</button></div>`,`${labels[doc.type]} · ${esc(f.issuer||f.well||'')} · ${events.length} seriales`)+`<section class="panel"><dl class="event-fields">${(commonKeys[doc.type]||[]).map(key=>`<div><dt>${esc(fieldDefinitions[doc.type].find(([k])=>k===key)?.[1]||key)}</dt><dd>${esc(f[key]||'—')}</dd></div>`).join('')}</dl></section><section class="panel">${eventRows(events,doc.type)}</section>`;}
function detailView(){const tool=data.tools.find(t=>t.serial===detail);if(!tool)return toolsView();const events=historyEngine(detail,data.events);return `<button class="subtle" data-page="tools">← Herramientas</button>`+heading(esc(detail),status(tool.status),`${toolGroup(detail)} · ${events.length} eventos · Fecha técnica: ${date(tool.statusDate)}`)+`<section class="timeline">${events.map(e=>`<article class="panel"><div class="panel-title"><div><p class="eyebrow">${date(e.date)} · ${labels[e.type]}</p><h2>${esc(e.fields.certificateNumber||e.fields.reportNumber||'BHA '+e.fields.bhaNumber)}</h2></div><div class="row-actions"><button class="subtle" data-report="${esc(e.documentId)}">Ver reporte</button><button class="subtle" data-edit="${esc(e.documentId)}">Editar</button><button class="subtle" data-pdf="${esc(e.documentId)}">PDF</button></div></div><p>${esc(e.fields.issuer||e.fields.well||'')}</p><details><summary>Detalles</summary><dl class="event-fields">${fieldDefinitions[e.type].map(([k,l])=>`<div><dt>${esc(l)}</dt><dd>${esc(e.fields[k]||'—')}</dd></div>`).join('')}</dl></details></article>`).join('')}</section>`;}
function inputField(def,value,index,common=false){const [key,label,kind]=def;const attrs=common?`data-common="${key}"`:`data-field="${key}" data-record="${index}"`;return `<label>${esc(label)}${kind==='textarea'?`<textarea ${attrs} rows="2">${esc(value)}</textarea>`:kind==='status'?`<select ${attrs}><option value="">Seleccionar</option>${states.map(s=>`<option value="${s}" ${s===value?'selected':''}>${labels[s]}</option>`).join('')}</select>`:`<input ${attrs} type="${kind==='date'?'date':'text'}" value="${esc(value)}" maxlength="12000">`}</label>`;}
function recordCard(r,i,d){const errors=matrixValidator(d.type,r);return `<details class="record" id="record-${i}" ${errors.length?'open':''}><summary><span class="record-summary"><b id="serial-label-${i}">${esc(r.serial||'Nuevo serial')}</b><span class="badge ${errors.length?'warning':'success'}" id="record-badge-${i}">${errors.length?'Por completar':'Completo'}</span></span></summary><div class="fields"><label>Serial<input data-field="serial" data-record="${i}" value="${esc(r.serial)}" maxlength="64"></label>${(fieldDefinitions[d.type]||[]).filter(([key])=>!(commonKeys[d.type]||[]).includes(key)).map(def=>inputField(def,r.fields[def[0]]||'',i)).join('')}</div><div class="validation" id="validation-${i}" ${errors.length?'':'hidden'}>${esc(humanError(errors.join(' ')))}</div><details><summary>Ver origen</summary>${(r.evidence||[]).map(e=>`<p class="evidence">Página ${e.page} · ${esc(e.line)}</p>`).join('')||'<p class="muted">Agregado manualmente.</p>'}</details><button class="subtle" data-remove="${i}">Quitar serial del reporte</button></details>`;}
function editorView(){const d=editor;const defs=fieldDefinitions[d.type]||[];const common=d.records[0]?.fields||d.commonFields||{};return `<button class="subtle" data-action="close-editor">← Documentos</button>`+heading(d.existing?'Editar reporte':'Completar documento',`<button class="secondary" data-pdf="${esc(d.id)}">Ver PDF</button>`,esc(d.name))+`<section class="panel">${!d.existing?`<label>Tipo<select id="type">${['UNKNOWN','INSPECTION','REPAIR','BHA'].map(t=>`<option value="${t}" ${d.type===t?'selected':''}>${labels[t]}</option>`).join('')}</select></label>`:''}<div class="fields">${defs.filter(([key])=>(commonKeys[d.type]||[]).includes(key)).map(def=>inputField(def,common[def[0]]||'',0,true)).join('')}</div>${d.error?`<p class="callout danger">${esc(humanError(d.error))}</p>`:''}<div id="document-validation" class="validation" ${documentErrors(d).length?'':'hidden'}>${esc(humanError(documentErrors(d).slice(0,4).join(' ')))}</div></section>${d.records.map((r,i)=>recordCard(r,i,d)).join('')}<div class="review-actions"><button class="secondary" data-action="add" ${d.type==='UNKNOWN'?'disabled':''}>+ Agregar serial</button><button class="primary" data-action="save" ${busy?'disabled':''}>${d.existing?'Guardar cambios':'Guardar reporte'}</button></div>`;}
function render(){if(!user){root.innerHTML=authView();return;}if(!demo&&!user.emailVerified){root.innerHTML=`<section class="verify panel"><h1>Verifica tu correo</h1><p>${esc(user.email)}</p><button class="primary" data-action="refresh">Ya verifiqué mi correo</button><button class="secondary" data-action="verify">Reenviar enlace</button><button class="subtle" data-action="logout">Cerrar sesión</button></section>`;return;}root.innerHTML=shell(editor?editorView():detail?detailView():reportId?reportView():page==='upload'?upload():page==='tools'?toolsView():page==='documents'?documentsView():page==='calendar'?calendarView(data,calendarMonth,selectedDay):dashboard());}
async function persist(entry){await archive.put(owner(),entry);}
function savePendingEdit(){if(!editor||editor.existing)return;const entry=structuredClone({...editor,status:'needs_attention',error:''});delete entry.existing;delete entry.baseRevision;const i=inbox.findIndex(x=>x.id===entry.id);inbox[i]=entry;const account=owner();pendingWrite=pendingWrite.then(()=>archive.put(account,entry)).catch(e=>notify('No se pudo conservar el cambio: '+e.message));}
async function refreshData(){data=await repo.load();for(const entry of inbox){if(data.documents.some(d=>d.id===entry.id)&&entry.status!=='saved'){entry.status='saved';entry.error='';await persist(entry);}}}
async function activate(current,local=false){
  const token=++epoch;user=current;demo=local;repo=local?new DemoRepository():new FirebaseRepository(current.uid);data=emptyState();inbox=[];editor=null;detail='';reportId='';
  if(!local&&!current.emailVerified){busy=false;render();return;}
  busy=true;progress='Abriendo documentos…';render();const account=owner();
  try{const [saved,localEntries]=await Promise.allSettled([repo.load(),archive.list(account)]);if(token!==epoch)return;
    if(saved.status==='fulfilled')data=saved.value;else notify('No se pudo sincronizar: '+saved.reason.message);
    if(localEntries.status==='fulfilled')inbox=localEntries.value;else notify('No se pudo abrir el archivo local: '+localEntries.reason.message);
    for(const entry of inbox)if(data.documents.some(d=>d.id===entry.id)){entry.status='saved';entry.error='';}
  }catch(e){notify(e.message);}finally{if(token===epoch){busy=false;progress='';render();}}
  if(token===epoch&&inbox.some(e=>e.status==='queued'||e.status==='waiting'))await processQueue();
}
function cleanup(){if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl='';}document.querySelector('dialog')?.remove();}
async function showPDF(id){cleanup();const file=await pdfStore('get',owner()+':'+id);if(!file){notify('Este PDF está en el dispositivo donde se cargó. Puedes volver a cargarlo aquí sin duplicar sus datos.');return;}pdfUrl=URL.createObjectURL(file);const dialog=document.createElement('dialog');dialog.innerHTML=`<div class="panel-title"><h2>PDF original</h2><button data-action="close-pdf" class="secondary">Cerrar</button></div><iframe title="PDF original" src="${pdfUrl}"></iframe><a class="secondary" href="${pdfUrl}" target="_blank" rel="noopener">Abrir en otra pestaña</a>`;document.body.append(dialog);dialog.addEventListener('close',cleanup,{once:true});dialog.showModal();}
async function processEntry(entry){
  if(entry.status==='queued') {
    try{const file=await pdfStore('get',owner()+':'+entry.id);if(!file)throw new Error('No está disponible el PDF original.');const {pages}=await textExtractor(file);Object.assign(entry,{pages,...analyze(pages),status:'needs_attention',error:''});await persist(entry);}catch(e){entry.status='needs_attention';entry.error=e.message;await persist(entry);return;}
  }
  if(documentErrors(entry).length){entry.status='needs_attention';await persist(entry);return;}
  try{await repo.save({...entry,validationMode:'automatic'});entry.status='saved';entry.error='';}
  catch(e){if(/PDF ya fue guardado/.test(e.message)){entry.status='saved';entry.error='';}else{entry.status=!navigator.onLine?'waiting':'needs_attention';entry.error=e.message;}}
  await persist(entry);
}
async function processQueue(entries=inbox.filter(e=>e.status==='queued'||e.status==='waiting')){if(busy)return;busy=true;try{for(let i=0;i<entries.length;i++){progress=`Procesando ${i+1} de ${entries.length}: ${entries[i].name}`;render();await processEntry(entries[i]);}try{await refreshData();}catch(e){notify('Los archivos están conservados. Falta sincronizar: '+e.message);}}finally{busy=false;progress='';render();}}
async function ingest(files){if(busy)return;busy=true;failures=[];editor=null;detail='';reportId='';page='upload';let duplicates=0;const queued=[];render();try{
  navigator.storage?.persist?.().catch(()=>{});
  for(let index=0;index<files.length;index++){const file=files[index];progress=`Conservando ${index+1} de ${files.length}: ${file.name}`;render();try{
    if(file.size>25*1024*1024)throw new Error('Supera el límite de 25 MB.');const bytes=await file.arrayBuffer();if(!new TextDecoder().decode(bytes.slice(0,1024)).includes('%PDF-'))throw new Error('El archivo no es un PDF válido.');
    const id=await digest(bytes);const captured=await archive.capture(owner(),file,id);const existing=inbox.find(e=>e.id===id);const entry=existing||captured.entry;if(!existing)inbox.push(entry);
    if(data.documents.some(d=>d.id===id)){entry.status='saved';entry.error='';await persist(entry);duplicates++;continue;}
    if(!captured.created){duplicates++;continue;}queued.push(entry);
  }catch(e){failures.push(file.name+': '+e.message);}}
  for(let i=0;i<queued.length;i++){progress=`Procesando ${i+1} de ${queued.length}: ${queued[i].name}`;render();await processEntry(queued[i]);}
  try{await refreshData();}catch(e){failures.push('Pendiente de sincronización: '+e.message);}
  page=failures.length?'upload':'documents';notify(`${queued.filter(e=>e.status==='saved').length} guardados${duplicates?` · ${duplicates} ya estaban cargados`:''}${pending().length?` · ${pending().length} por completar`:''}.`);
}finally{busy=false;progress='';render();}}
function openEditor(id){const doc=data.documents.find(d=>d.id===id);if(doc){editor={...doc,existing:true,baseRevision:doc.revision||0,records:data.events.filter(e=>e.documentId===id).map(e=>({serial:e.serial,rawSerial:e.rawSerial,sourceEventId:e.id,evidence:e.evidence||[],fields:{...e.fields}}))};}else{const entry=inbox.find(x=>x.id===id);if(!entry)return;editor={...structuredClone(entry),existing:false};}detail='';reportId='';page='documents';render();}
function updateValidation(){if(!editor)return;editor.records.forEach((r,i)=>{const errors=matrixValidator(editor.type,r);const v=document.querySelector('#validation-'+i);if(v){v.textContent=humanError(errors.join(' '));v.hidden=!errors.length;}const badge=document.querySelector('#record-badge-'+i);if(badge){badge.textContent=errors.length?'Por completar':'Completo';badge.className='badge '+(errors.length?'warning':'success');}});const errors=documentErrors(editor);const v=document.querySelector('#document-validation');if(v){v.textContent=humanError(errors.slice(0,4).join(' '));v.hidden=!errors.length;}}
async function saveEditor(){const errors=documentErrors(editor);if(errors.length){updateValidation();notify(humanError(errors[0]));return;}busy=true;progress='Guardando cambios…';const editing=editor.existing;render();try{
  await pendingWrite;const saved=await repo.save({...editor,validationMode:'corrected'},{editing,baseRevision:editor.baseRevision||0});
  let local=inbox.find(e=>e.id===editor.id);if(local){Object.assign(local,{type:editor.type,template:editor.template,records:structuredClone(editor.records),status:'saved',error:'',savedRevision:saved.revision});await persist(local);}
  const id=editor.id;editor=null;await refreshData();reportId=id;page='documents';notify(editing?'Reporte actualizado.':'Reporte guardado.');
}catch(error){if(/otra sesión/.test(error.message)){try{await refreshData();}catch{}}throw error;}finally{busy=false;progress='';render();}}
function authError(e){return ({'auth/invalid-credential':'Correo o contraseña incorrectos.','auth/email-already-in-use':'Ese correo ya tiene una cuenta.','auth/too-many-requests':'Demasiados intentos. Intenta más tarde.','auth/weak-password':'La contraseña no cumple la política configurada.','auth/operation-not-allowed':'Habilita Email/Password en Firebase.','auth/network-request-failed':'Revisa tu conexión.'})[e.code]||e.message||'No fue posible completar la operación.';}
function openModal(html){cleanup();const dialog=document.createElement('dialog');dialog.className='action-dialog';dialog.innerHTML=html;document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();dialog.querySelector('input:not([type=hidden]),button')?.focus();}
async function eraseData(){busy=true;progress='Eliminando datos…';document.querySelector('dialog')?.close();render();try{await pendingWrite;await repo.clearAll();await archive.clear(owner());data=emptyState();inbox=[];failures=[];editor=null;detail='';reportId='';documentFilter='ALL';page='documents';notify('Información eliminada. Tu cuenta sigue activa.');}catch(error){try{data=await repo.load();}catch{}notify('El borrado no terminó. Vuelve a Eliminar datos para completarlo. '+error.message);}finally{busy=false;progress='';render();}}
document.addEventListener('submit',async e=>{if(e.target.getAttribute('id')==='schedule-form'){e.preventDefault();const button=e.target.querySelector('button[type=submit],button.primary');button.disabled=true;try{const values=Object.fromEntries(new FormData(e.target));const old=data.scheduledEvents?.find(x=>x.id===values.id);await repo.saveSchedule({...old,...values});await refreshData();selectedDay=values.date;calendarMonth=values.date.slice(0,7);document.querySelector('dialog')?.close();render();notify('Evento agendado.');}catch(err){let message=e.target.querySelector('[role=alert]');if(!message){message=document.createElement('p');message.setAttribute('role','alert');e.target.prepend(message);}message.textContent=err.message;button.disabled=false;}}if(e.target.id==='erase-form'){e.preventDefault();if(new FormData(e.target).get('phrase')==='ELIMINAR')await eraseData();}});
document.addEventListener('submit',async e=>{if(e.target.id!=='auth-form')return;e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const f=new FormData(e.target);if(authMode==='reset'){await session.reset(f.get('email'));notify('Si la cuenta existe, recibirás un enlace.');}else if(authMode==='register'){await session.register(f.get('email'),f.get('password'));notify('Cuenta creada. Revisa tu correo.');}else await session.login(f.get('email'),f.get('password'));}catch(err){notify(authError(err));}finally{button.disabled=false;}});
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button||button.disabled)return;try{
  const action=button.dataset.action;
  if(busy&&action!=='close-pdf'&&!button.dataset.pdf)return;
  if(action==='dismiss-dialog'){document.querySelector('dialog')?.close();return;}
  if(action==='erase-start'){openModal(`<h2>¿Eliminar toda tu información?</h2><p>Se borrarán herramientas, reportes, historiales y agenda de ${demo?'este archivo local':'tu cuenta'}, además de los PDFs y pendientes de este dispositivo.</p><p>Los datos no se pueden recuperar desde la app. Puedes descargar el Excel antes de continuar.</p><div class="row-actions"><button class="secondary" data-action="dismiss-dialog">Cancelar</button><button class="danger-button secondary" data-action="erase-confirm">Sí, continuar</button></div>`);return;}
  if(action==='erase-confirm'){openModal('<h2>Confirmación final</h2><form id="erase-form"><label>Escribe ELIMINAR para borrar toda la información<input name="phrase" required pattern="ELIMINAR" autocomplete="off"></label><div class="row-actions"><button type="button" class="secondary" data-action="dismiss-dialog">Cancelar</button><button class="primary danger-button">Eliminar definitivamente</button></div></form>');return;}
  if(action==='new-schedule'){openModal(scheduleForm({date:selectedDay}));return;}
  if(button.dataset.scheduleEdit){openModal(scheduleForm(data.scheduledEvents.find(x=>x.id===button.dataset.scheduleEdit)));return;}
  if(button.dataset.scheduleDelete){if(confirm('¿Cancelar este evento programado?')){await repo.deleteSchedule(button.dataset.scheduleDelete);await refreshData();render();}return;}
  if(button.dataset.day){selectedDay=button.dataset.day;render();return;}
  if(button.dataset.month){const [y,m]=calendarMonth.split('-').map(Number);const d=new Date(y,m-1+Number(button.dataset.month),1);calendarMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selectedDay=calendarMonth+'-01';render();return;}
  if(action==='calendar-today'){selectedDay=localDay();calendarMonth=selectedDay.slice(0,7);render();return;}
  if(button.dataset.group){groupFilter=button.dataset.group;render();return;}
  if(button.dataset.docFilter){documentFilter=button.dataset.docFilter;render();return;}
  if(action==='excel'){const view=button.dataset.scope==='view';const sheets=reportModel(data,{group:view?groupFilter:'ALL',search:view?serialNormalizer(search):'',pending:pending()});if(!sheets.some(s=>s.rows.length)){notify('No hay información para exportar.');return;}downloadExcel(sheets,view?(groupFilter==='ALL'?'vista':groupFilter):'todos');notify('Excel descargado.');return;}
  if(button.dataset.page){page=button.dataset.page;detail='';reportId='';editor=null;render();return;}
  if(button.dataset.pdf){await showPDF(button.dataset.pdf);return;}
  if(action==='close-pdf'){document.querySelector('dialog')?.close();return;}
  if(busy)return;
  if(button.dataset.auth){authMode=button.dataset.auth;render();}
  if(button.dataset.serial){detail=button.dataset.serial;reportId='';editor=null;page='tools';render();}
  if(button.dataset.report){const id=button.dataset.report;if(data.documents.some(d=>d.id===id)){reportId=id;detail='';editor=null;page='documents';render();}else openEditor(id);}
  if(button.dataset.edit)openEditor(button.dataset.edit);
  if(button.dataset.remove!==undefined){editor.records.splice(+button.dataset.remove,1);savePendingEdit();render();}
  if(action==='demo'){sessionStorage.setItem('tooltrace-demo','1');await activate({uid:'demo',email:'Mi archivo local',emailVerified:true},true);}
  if(action==='logout'){await pendingWrite;cleanup();sessionStorage.removeItem('tooltrace-demo');++epoch;if(!demo)await session.logout();demo=false;user=null;repo=null;data=emptyState();inbox=[];failures=[];detail='';editor=null;reportId='';search='';groupFilter='ALL';documentFilter='ALL';render();}
  if(action==='refresh'){const current=await session.refresh();if(current.emailVerified)await activate(current);else notify('Abre el enlace de verificación del correo.');}
  if(action==='verify'){await session.verify();notify('Enlace enviado.');}
  if(action==='add'){const shared=editor.records[0]?.fields||editor.commonFields||{};editor.records.push({serial:'',rawSerial:'',evidence:[],fields:Object.fromEntries(fieldDefinitions[editor.type].map(([key])=>[key,(commonKeys[editor.type]||[]).includes(key)?shared[key]||'':'']))});savePendingEdit();render();}
  if(action==='close-editor'){editor=null;page='documents';render();}
  if(action==='save')await saveEditor();
  if(action==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tooltrace-datos.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(action==='install'){if(installPrompt){await installPrompt.prompt();installPrompt=null;}else notify('Usa Instalar aplicación en tu navegador. En iPhone: Compartir → Añadir a pantalla de inicio.');}
}catch(error){notify(authError(error));}});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='files')ingest([...el.files]).catch(err=>notify(err.message));if(el.id==='type'&&editor&&!editor.existing){Object.assign(editor,analyze(editor.pages||[],el.value),{error:''});savePendingEdit();render();}});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='search'){search=el.value;document.querySelector('#tool-results').innerHTML=toolRows(filteredTools().slice(0,page==='dashboard'?8:Infinity));}if(!editor)return;if(el.dataset.common){editor.commonFields={...editor.commonFields,[el.dataset.common]:el.value};for(const r of editor.records)r.fields[el.dataset.common]=el.value;updateValidation();savePendingEdit();}if(el.dataset.field){const r=editor.records[+el.dataset.record];if(el.dataset.field==='serial'){r.serial=el.value;document.querySelector('#serial-label-'+el.dataset.record).textContent=el.value||'Nuevo serial';}else r.fields[el.dataset.field]=el.value;updateValidation();savePendingEdit();}});
document.addEventListener('dragover',e=>{if(page==='upload'){e.preventDefault();document.querySelector('.dropzone')?.classList.add('dragging');}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.querySelector('.dropzone')?.classList.remove('dragging');});document.addEventListener('drop',e=>{if(page==='upload'&&user){e.preventDefault();document.querySelector('.dropzone')?.classList.remove('dragging');ingest([...e.dataTransfer.files]).catch(err=>notify(err.message));}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('online',()=>{render();if(user&&!editor&&!busy)processQueue().catch(e=>notify(e.message));});window.addEventListener('offline',()=>render());
if(sessionStorage.getItem('tooltrace-demo')==='1'){demo=true;activate({uid:'demo',email:'Mi archivo local',emailVerified:true},true);}
session.watch(async current=>{if(demo)return;if(current)await activate(current);else{++epoch;user=null;data=emptyState();inbox=[];editor=null;render();}});
render();
if('serviceWorker'in navigator&&import.meta.env.PROD){navigator.serviceWorker.register('./sw.js').then(reg=>{reg.update();const activate=()=>reg.waiting?.postMessage({type:'ACTIVATE_UPDATE'});activate();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',activate);});}).catch(()=>{});}
